"""
ClaudeCut — build_xml.py: decision list (file, in, out, reason)  ->  FCP7 XML + cut plan.

Back end of the pipeline. In the finished tool the list below comes from the AI
(Whisper -> Claude reads transcripts + briefing). Here it sits as the result of
exactly that step. In/out in SECONDS (as Whisper delivers them); ffprobe converts
to frames per clip -> robust with mixed fps.

Writes a video AND an audio track. The real file properties (channels, rate,
resolution) are measured via ffprobe and patched into the XML afterwards, so that
Premiere can auto-link the media (otherwise channel mismatch on relink).
"""

import copy
import pathlib
import subprocess
import sys
import urllib.parse
import xml.etree.ElementTree as ET
from fractions import Fraction

import opentimelineio as otio

# Force the Windows console to UTF-8 (otherwise cp1252 mangles umlauts/→ in messages).
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

ROOT = pathlib.Path(__file__).parent

# --- Job (briefing, sequence format, EDL) from cut.py ------------------------
# cut.py is generated by prep.py and the EDL filled while reading the transcripts.
# Split on purpose: build_xml.py is the pure translator, cut.py is the job.
try:
    from cut import BRIEFING, CLIPS_DIR, DROPPED, EDL, SEQ_FPS, SEQ_H, SEQ_W
except ImportError:
    sys.exit("No cut.py found — first run `python prep.py \"<footage folder>\"` "
             "(creates cut.py + transcripts.md), then fill the EDL in cut.py.")

CLIPS = pathlib.Path(CLIPS_DIR)
OUT_XML = ROOT / "cut.xml"
OUT_PLAN = ROOT / "cut_plan.md"

if not EDL:
    sys.exit("EDL in cut.py is empty — first enter the soundbite selection "
             "(see transcripts.md), then run build_xml.py again.")


# --- ffprobe helper ----------------------------------------------------------
def ffprobe(path, stream, entries):
    return subprocess.check_output([
        "ffprobe", "-v", "error", "-select_streams", stream,
        "-show_entries", entries,
        "-of", "default=noprint_wrappers=1:nokey=1", str(path),
    ]).decode().strip().splitlines()


def media_info(path: pathlib.Path) -> dict:
    """Everything the XML needs to know about the file — measured once per clip."""
    num, den = ffprobe(path, "v:0", "stream=r_frame_rate")[0].split("/")
    rate = float(Fraction(int(num), int(den)))
    w = int(ffprobe(path, "v:0", "stream=width")[0])
    h = int(ffprobe(path, "v:0", "stream=height")[0])
    # Use the VIDEO stream's own length, not format=duration (which follows the
    # longest stream — often audio). When audio runs longer than video it
    # overstates the frame count and Premiere blacks the clip. Prefer the exact
    # nb_frames when ffprobe knows it.
    vdur = ffprobe(path, "v:0", "stream=duration")
    if vdur and vdur[0] not in ("", "N/A"):
        dur_sec = float(vdur[0])
    else:
        dur_sec = float(subprocess.check_output([
            "ffprobe", "-v", "error", "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1", str(path)]).decode().strip())
    nbf = ffprobe(path, "v:0", "stream=nb_frames")
    nb = int(nbf[0]) if nbf and nbf[0] not in ("", "N/A") else None
    total_frames = nb if (nb and nb > 0) else round(dur_sec * rate)
    channels = int(ffprobe(path, "a:0", "stream=channels")[0])
    samplerate = int(ffprobe(path, "a:0", "stream=sample_rate")[0])
    return {
        "rate": rate, "width": w, "height": h,
        "total_frames": total_frames,
        "channels": channels, "samplerate": samplerate,
    }


def make_clip(path, info, in_frame, dur_frames):
    """Fresh clip instance (one per track — otio forbids a duplicate parent)."""
    rate = info["rate"]
    return otio.schema.Clip(
        name=path.stem,
        media_reference=otio.schema.ExternalReference(
            target_url=path.as_uri(),
            available_range=otio.opentime.TimeRange(
                otio.opentime.RationalTime(0, rate),
                otio.opentime.RationalTime(info["total_frames"], rate))),
        source_range=otio.opentime.TimeRange(
            otio.opentime.RationalTime(in_frame, rate),
            otio.opentime.RationalTime(dur_frames, rate)),
    )


# --- Build timeline (video only; we add audio by hand below) -----------------
# otio's fcp_xml adapter only writes empty audio stubs -> we build the audio track
# ourselves in post-processing from the finished video clip items.
timeline = otio.schema.Timeline(name="ClaudeCut")
v_track = otio.schema.Track(name="V1", kind=otio.schema.TrackKind.Video)
timeline.tracks.append(v_track)

print(f"Briefing: {BRIEFING}\n")
infos, rows, seq_pos = {}, [], []
tl_sec = 0.0  # running timeline position in seconds -> sequence frames @ SEQ_FPS
for filename, in_sec, out_sec, reason in EDL:
    path = (CLIPS / filename).resolve()
    info = media_info(path)
    infos[filename] = info

    in_frame = round(in_sec * info["rate"])
    dur_frames = round((out_sec - in_sec) * info["rate"])

    # Never reference past the last real video frame — audio can run longer than
    # the picture, so a selected out can land in the audio-only tail -> Premiere
    # shows black. Clamp to the measured media.
    if in_frame >= info["total_frames"]:
        sys.exit(f"EDL in-point {in_sec:.2f}s is past the video end of {filename}")
    if in_frame + dur_frames > info["total_frames"]:
        dur_frames = info["total_frames"] - in_frame

    # Timeline position in the target frame rate (independent of the source fps)
    dur_sec = dur_frames / info["rate"]
    s = round(tl_sec * SEQ_FPS)
    tl_sec += dur_sec
    e = round(tl_sec * SEQ_FPS)
    # Premiere reads a clipitem's <in>/<out> in the SEQUENCE timebase, not the
    # source clip rate -> express the source in-point in sequence frames.
    in_seq = round(in_sec * SEQ_FPS)
    seq_pos.append((s, e, in_seq))

    v_track.append(make_clip(path, info, in_frame, dur_frames))

    rows.append((filename, info["rate"], in_sec, out_sec, dur_frames / info["rate"], reason))
    print(f"  {filename[:28]:28s} @{info['rate']:g}fps  {in_sec:6.2f}->{out_sec:6.2f}s "
          f"({dur_frames/info['rate']:4.1f}s, {info['channels']}ch)")

total_sec = sum(r[4] for r in rows)
print(f"\nTotal length: {total_sec:.1f}s")

# --- Write FCP7 XML ----------------------------------------------------------
otio.adapters.write_to_file(timeline, str(OUT_XML), adapter_name="fcp_xml")


# --- Patch XML: enter real file properties -----------------------------------
# otio leaves <video/>/<audio/> empty -> Premiere guesses 1 mono channel and
# refuses the relink. We enter the measured values per <file>.
def patch_file_media(file_el, info):
    for m in file_el.findall("media"):
        file_el.remove(m)
    media = ET.SubElement(file_el, "media")
    video = ET.SubElement(media, "video")
    vsc = ET.SubElement(video, "samplecharacteristics")
    ET.SubElement(vsc, "width").text = str(info["width"])
    ET.SubElement(vsc, "height").text = str(info["height"])
    audio = ET.SubElement(media, "audio")
    asc = ET.SubElement(audio, "samplecharacteristics")
    ET.SubElement(asc, "depth").text = "16"
    ET.SubElement(asc, "samplerate").text = str(info["samplerate"])
    ET.SubElement(audio, "channelcount").text = str(info["channels"])


tree = ET.parse(OUT_XML)
root = tree.getroot()

# (0) Set the sequence format: frame rate, resolution, pixel aspect, timeline positions.
# otio leaves <format/> empty (-> Premiere assumes 640×480/4:3) and lays out the
# positions in the source fps. We enter the target format and recompute start/end to SEQ_FPS.
seq = root.find(".//sequence")
seq.find("rate/timebase").text = str(SEQ_FPS)
seq.find("rate/ntsc").text = "FALSE"
seq.find("duration").text = str(seq_pos[-1][1])

vmedia = seq.find("media/video")
fmt = vmedia.find("format")
for ch in list(fmt):
    fmt.remove(ch)
sc = ET.SubElement(fmt, "samplecharacteristics")
rt = ET.SubElement(sc, "rate")
ET.SubElement(rt, "timebase").text = str(SEQ_FPS)
ET.SubElement(rt, "ntsc").text = "FALSE"
ET.SubElement(sc, "width").text = str(SEQ_W)
ET.SubElement(sc, "height").text = str(SEQ_H)
ET.SubElement(sc, "pixelaspectratio").text = "square"
ET.SubElement(sc, "fielddominance").text = "none"

for i, vci in enumerate(vmedia.findall("track/clipitem")):
    # otio emits two identical <rate> blocks per clipitem; keep one.
    for extra in vci.findall("rate")[1:]:
        vci.remove(extra)
    s, e, in_seq = seq_pos[i]
    dur = e - s
    # Premiere reads clipitem <in>/<out> in the SEQUENCE timebase, not the source
    # clip rate -> express the clipitem rate AND source in/out in sequence frames
    # (source dur == timeline dur, no retime). The real media length stays correct
    # via the <file> rate. Without this, mixed fps (e.g. 59.94 source in a 30 fps
    # timeline) reads ~2x off -> short clips run past their end -> black.
    rate_el = vci.find("rate")
    rate_el.find("timebase").text = str(SEQ_FPS)
    rate_el.find("ntsc").text = "FALSE"
    vci.find("start").text = str(s)   # timeline position now in target-fps frames
    vci.find("end").text = str(e)
    vci.find("in").text = str(in_seq)
    vci.find("out").text = str(in_seq + dur)
    vci.find("duration").text = str(dur)

# (a) Enter file specs
patched = 0
for file_el in root.iter("file"):
    name_el = file_el.find("name")
    if name_el is None:
        continue
    decoded = urllib.parse.unquote(name_el.text)  # otio encodes spaces as %20
    if decoded in infos:  # only fully defined <file>
        patch_file_media(file_el, infos[decoded])
        patched += 1


# (b) Build stereo audio tracks from the video clip items
def sub(parent, tag, text=None):
    e = ET.SubElement(parent, tag)
    if text is not None:
        e.text = str(text)
    return e


def link_block(parent, ref, mediatype, trackindex, clipindex):
    lk = ET.SubElement(parent, "link")
    sub(lk, "linkclipref", ref)
    sub(lk, "mediatype", mediatype)
    sub(lk, "trackindex", trackindex)
    sub(lk, "clipindex", clipindex)


nch = max(info["channels"] for info in infos.values())  # stereo -> 2 audio tracks
seq_media = root.find(".//sequence/media")
audio_sec = seq_media.find("audio")
for t in audio_sec.findall("track"):          # remove otio's empty stubs
    audio_sec.remove(t)
a_tracks = [ET.SubElement(audio_sec, "track") for _ in range(nch)]

v_items = seq_media.findall("video/track/clipitem")
for idx, vci in enumerate(v_items, 1):
    vid_id = vci.get("id")
    file_id = vci.find("file").get("id")
    audio_ids = [f"clipitem-a{ch+1}-{idx}" for ch in range(nch)]

    # Link group: video + all audio channels belong together
    members = [(vid_id, "video", 1)] + [(audio_ids[ch], "audio", ch + 1) for ch in range(nch)]

    def add_links(target):
        for ref, mt, ti in members:
            link_block(target, ref, mt, ti, idx)

    add_links(vci)  # links on the video clip too

    for ch in range(nch):
        aci = ET.SubElement(a_tracks[ch], "clipitem")
        aci.set("id", audio_ids[ch])
        sub(aci, "name", vci.find("name").text)
        aci.append(copy.deepcopy(vci.find("rate")))
        sub(aci, "duration", vci.find("duration").text)
        sub(aci, "start", vci.find("start").text)
        sub(aci, "end", vci.find("end").text)
        sub(aci, "in", vci.find("in").text)
        sub(aci, "out", vci.find("out").text)
        ET.SubElement(aci, "file").set("id", file_id)  # same file, just a reference
        st = ET.SubElement(aci, "sourcetrack")
        sub(st, "mediatype", "audio")
        sub(st, "trackindex", ch + 1)
        add_links(aci)

# (c) Fix the media path dialect: Premiere on Windows relinks reliably only from
# the file://localhost/ form. otio writes file:///C:/... which Premiere's FCP7
# importer often fails to locate (media comes in offline).
for pathurl in root.iter("pathurl"):
    if pathurl.text and pathurl.text.startswith("file:///"):
        pathurl.text = "file://localhost/" + pathurl.text[len("file:///"):]

tree.write(OUT_XML, encoding="utf-8", xml_declaration=True)
print(f"XML patched: {patched} file specs + {nch} audio tracks ({len(v_items)} clips, linked).")

# --- Write cut_plan.md (human-readable) --------------------------------------
with open(OUT_PLAN, "w", encoding="utf-8") as f:
    f.write("# Cut plan — ClaudeCut\n\n")
    f.write(f"**Briefing:** {BRIEFING}\n\n")
    f.write(f"**Total length:** {total_sec:.1f}s · {len(rows)} clips\n\n")
    f.write("## Used (in order)\n\n")
    for i, (fn, rate, a, b, dur, reason) in enumerate(rows, 1):
        f.write(f"{i}. **{fn}** @{rate:g}fps — `{a:.2f}–{b:.2f}s` ({dur:.1f}s)\n"
                f"   - {reason}\n\n")
    f.write("## Dropped\n\n")
    for fn, reason in DROPPED:
        f.write(f"- **{fn}** — {reason}\n")

print(f"\nWritten:\n  {OUT_XML}\n  {OUT_PLAN}")
